import "./ui/global.css"
import { font } from './ui/fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  )
}
